### PR TITLE
Add sdist and wheel to the Release assets (#339)

### PR DESCRIPTION
**Pull request by lalver1**
Fixes PeopleForBikes/brokenspoke-analyzer#339

### CODE REVIEW

**Comment by lalver1** [comment]
I think this `release` job may conflict with the shared `release` job @rgreinho, especially with the lines
```
- name: Publish the release
  uses: softprops/action-gh-release@v1
  with:
    body: ${{ steps.changelog_reader.outputs.changes }}
```
but we can clean it up.

**Comment by rgreinho** [comment]
Ah, I see. I did not think of it :/

So I went though the issues, and I found 2 that may be promising:
- https://github.com/softprops/action-gh-release/issues/203
- https://github.com/softprops/action-gh-release/issues/323

The first one shows that the `softprops/action-gh-release` action should upload assets to an existing release. The second one gives a workaround using the `gh` cli tool.

Could you try validating that the `softprops/action-gh-release` action will update an existing release?

**Comment by lalver1** [comment]
Thanks for the tip @rgreinho ! I'll test `softprops/action-gh-release` for updating the assets of an existing release.

**Comment by lalver1** [comment]
Looks like it works @rgreinho ! If the `softprops/action-gh-release` action is ran in a different workflow, any files included in the action are appended to an existing release. This is the simple repo I set up to test it: [gh-release-test](https://github.com/lalver1/gh-release-test). If you don't mind browsing over the 2 workflows (one mimics our shared `release`) just to make sure it reflects the actual workflows in `brokenspoke-analyzer` that would be good. Then I can update this PR. Thanks!

**Comment by rgreinho** [comment]
Awesome! That looks great @lalver1! Merging 👍

**Review by rgreinho — APPROVED** [review]

**Pull request merged**
