### PR TITLE
Change neighborhood_reachable_roads_low_stress to neighborhood_reachable_roads_high_stress in connected census blocks calculation

### PR DESCRIPTION
**Pull request by mitchellhenke**
# Pull-Request

Thank you for all of the work that goes into the ratings! I have been working on understanding how the scores work and running them locally and came across what I think is a bug.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Description

This changes the table used when calculating census block connection scores. The second clause seemed like it was intended to be using the `neighborhood_reachable_roads_high_stress` table with the TRUE `high_stress` value and `hs` alias for the table. I'm not 100% sure, but I figured this could impact calculated scores if that was the case, so I wanted to open this to confirm first.

I've run the unit tests locally and they passed. I have also tested it manually on some smaller cities I'm familiar with, and in general the scores seem to be lower with this change, but still near the results on https://cityratings.peopleforbikes.org/.

I'm very much interested in helping where I can with this tool, so if there's anything I can do, just let me know. Thanks again for making this!

## Checklist

- [x] I have updated the documentation accordingly
- [ ] I have updated the Changelog (if applicable)

### CODE REVIEW

**Comment by lalver1** [comment]
Hi! We're so glad that you've been using the tool and thanks for the feedback! I agree, this does look like a bug, the second clause was likely meant to use `neighborhood_reachable_roads_high_stress table`. I'll look at this a little more closely and run a few cities before reviewing but my gut feeling is that we need to implement this change. Thanks again and talk to you soon!

**Review by lalver1 — APPROVED** [review]
This looks good! 👍 
If you can rebase and update the PR when you get a chance I'll go ahead and merge it.

**Comment by mitchellhenke** [comment]
@lalver1 done!

**Comment by lalver1** [comment]
👍

**Review by rgreinho — APPROVED** [review]
👍

**Pull request merged**
